# Generated by Django 3.2.5 on 2021-10-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20211024_0018'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
            preserve_default=False,
        ),
    ]
