# Generated by Django 3.2.5 on 2021-10-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20211024_0018'),
        ('review', '0002_auto_20211027_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='order',
        ),
        migrations.RemoveField(
            model_name='reviewrating',
            name='product',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_order_item', to='checkout.orderlineitem'),
            preserve_default=False,
        ),
    ]
